// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator, Family } from './types.ts'
import { creationOperators } from './data/creation.ts'
import { transformationOperators } from './data/transformation.ts'
import { filteringOperators } from './data/filtering.ts'
import { combinationOperators } from './data/combination.ts'
import { multicastingOperators } from './data/multicasting.ts'
import { errorHandlingOperators } from './data/error-handling.ts'
import { utilityOperators } from './data/utility.ts'
import { conditionalOperators } from './data/conditional.ts'
import { mathematicalOperators } from './data/mathematical.ts'
import { joinCreationOperators } from './data/join-creation.ts'
import { setOperationsOperators } from './data/set-operations.ts'
import { concurrencyOperators } from './data/concurrency.ts'
import { singleValueOperators } from './data/single-value.ts'
import { rateLimitingOperators } from './data/rate-limiting.ts'
import { testingOperators } from './data/testing.ts'
import { inspectionOperators } from './data/inspection.ts'
import { timingOperators } from './data/timing.ts'

export const operators: Operator[] = [
	...creationOperators,
	...transformationOperators,
	...filteringOperators,
	...combinationOperators,
	...multicastingOperators,
	...errorHandlingOperators,
	...utilityOperators,
	...conditionalOperators,
	...mathematicalOperators,
	...joinCreationOperators,
	...setOperationsOperators,
	...concurrencyOperators,
	...singleValueOperators,
	...rateLimitingOperators,
	...testingOperators,
	...inspectionOperators,
	...timingOperators,
]

export const families: Family[] = operators.reduce<Family[]>((acc, op) => {
	const existing = acc.find(f => f.name === op.family)
	if (existing) { existing.operators.push(op) }
	else acc.push({ name: op.family, description: '', operators: [op] })
	return acc
}, [])
