// pipeline/writer.ts

import { mkdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import type { TutorConfig } from '../src/curriculum/types.js'
import type { RawTopic } from './types.js'

function toKebab(s: string): string {
	return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function toCamelPrefix(s: string): string {
	return s
		.split(/[^a-zA-Z0-9]+/)
		.map((w, i) => i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase())
		.join('')
}

function escapeTemplate(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function escapeSingleQuote(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function serializeTopic(t: RawTopic): string {
	const examples = (t.examples ?? []).map(e =>
		`\t\t{ title: \`${escapeTemplate(e.title)}\`, content: \`${escapeTemplate(e.content)}\` },`
	).join('\n')
	const tags    = (t.tags    ?? []).map(s => `'${escapeSingleQuote(s)}'`).join(', ')
	const seeAlso = (t.seeAlso ?? []).map(s => `'${escapeSingleQuote(s)}'`).join(', ')
	return `\t{
\t\tname:        '${escapeSingleQuote(t.name)}',
\t\tcategory:    '${escapeSingleQuote(t.category)}',
\t\tdescription: \`${escapeTemplate(t.description)}\`,
\t\tdefinition:  \`${escapeTemplate(t.definition ?? '')}\`,
\t\tvisual:      \`${escapeTemplate(t.visual ?? '')}\`,
\t\texamples: [
${examples}
\t\t],
\t\ttags:    [${tags}],
\t\tseeAlso: [${seeAlso}],
\t},`
}

interface WrittenCategory { varName: string; kebab: string }

export function writeOutput(
	grouped:     Map<string, RawTopic[]>,
	tutorConfig: TutorConfig,
	outputDir:   string,
): void {
	const dataDir = join(outputDir, 'data')
	mkdirSync(dataDir, { recursive: true })

	const written: WrittenCategory[] = []

	for (const [category, topics] of grouped) {
		const kebab   = toKebab(category)
		const varName = toCamelPrefix(category) + 'Topics'
		const content =
			`// GENERATED by pipeline/run.ts — do not edit manually\n` +
			`import type { Topic } from '../types'\n\n` +
			`export const ${varName}: Topic[] = [\n` +
			topics.map(serializeTopic).join('\n') + '\n' +
			`]\n`
		writeFileSync(join(dataDir, `${kebab}.ts`), content, 'utf-8')
		written.push({ varName, kebab })
	}

	const imports = written.map(w => `import { ${w.varName} } from './data/${w.kebab}'`).join('\n')
	const spread  = written.map(w => `\t...${w.varName},`).join('\n')
	const indexContent =
		`// GENERATED by pipeline/run.ts — do not edit manually\n` +
		`import type { Topic, Family } from './types'\n` +
		`${imports}\n\n` +
		`export const topics: Topic[] = [\n${spread}\n]\n\n` +
		`export const families: Family[] = topics.reduce<Family[]>((acc, t) => {\n` +
		`\tconst existing = acc.find(f => f.name === t.category)\n` +
		`\tif (existing) { existing.topics.push(t) }\n` +
		`\telse acc.push({ name: t.category, description: '', topics: [t] })\n` +
		`\treturn acc\n` +
		`}, [])\n`
	writeFileSync(join(outputDir, 'index.ts'), indexContent, 'utf-8')

	const labelsLines = Object.entries(tutorConfig.labels)
		.filter(([, v]) => v !== undefined)
		.map(([k, v]) => `\t\t${k}: '${escapeSingleQuote(String(v))}',`)
		.join('\n')
	const configContent =
		`// GENERATED by pipeline/run.ts — do not edit manually\n` +
		`import type { TutorConfig } from './curriculum/types'\n\n` +
		`export const config: TutorConfig = {\n` +
		`\tdomainName: '${escapeSingleQuote(tutorConfig.domainName)}',\n` +
		`\tsystemPromptTemplate:\n` +
		`\t\t\`${escapeTemplate(tutorConfig.systemPromptTemplate)}\`,\n` +
		`\tdefaultCategory: '${escapeSingleQuote(tutorConfig.defaultCategory)}',\n` +
		`\tdefaultTopic:    '${escapeSingleQuote(tutorConfig.defaultTopic)}',\n` +
		`\tlabels: {\n${labelsLines}\n\t},\n` +
		`}\n`
	writeFileSync(join(outputDir, 'tutor.config.ts'), configContent, 'utf-8')

	console.log(`Wrote ${written.length} category files + index.ts + tutor.config.ts → ${outputDir}/`)
}
