// scripts/migrate-markdown.ts
import * as fs from 'fs'
import * as path from 'path'

const SOURCE_DIR = 'C:/Users/HP/Web/Frontend/rxjs/rxjs-operator-families/docs/operators'
const OUT_DIR    = path.join(process.cwd(), 'src/curriculum/data')

const FILE_TO_FAMILY: Record<string, string> = {
	'01.Creation.md':               'Creation',
	'02.Transformation.md':         'Transformation',
	'03.Filtering.md':              'Filtering',
	'04.Combination.md':            'Combination',
	'05.Multicasting.md':           'Multicasting',
	'06.Error-Handling.md':         'ErrorHandling',
	'07.Utility.md':                'Utility',
	'08.Conditional.md':            'Conditional',
	'09.Mathematical-Aggregate.md': 'Mathematical',
	'10.Join-Creation.md':          'JoinCreation',
	'11.Set-Operations.md':         'SetOperations',
	'12.Concurrency.md':            'Concurrency',
	'13.Single-Value.md':           'SingleValue',
	'14.Rate-Limiting.md':          'RateLimiting',
	'15.Testing.md':                'Testing',
	'16.Inspection-Side-Effects.md':'Inspection',
	'17.Timing.md':                 'Timing',
}

interface ParsedOperator {
	name: string
	description: string
	category: string
}

function parseFamilyFile(content: string): {
	description: string
	operators: ParsedOperator[]
	examples: Array<{ title: string; code: string }>
} {
	const lines = content.split('\n')

	// Family description: first non-empty paragraph after h1
	let description = ''
	let i = 1
	while (i < lines.length && !lines[i].trim()) i++
	while (i < lines.length && lines[i].trim() && !lines[i].startsWith('#')) {
		description += lines[i] + ' '
		i++
	}
	description = description.trim()

	// Operators: parse bullet points under ## Operator Categories
	const operators: ParsedOperator[] = []
	const opRegex = /^\s*-\s+\*\*`([^`]+)`\*\*(?:\s*\([^)]*\))?[:\s]+(.+)/
	let currentCategory = ''
	let inCategories = false

	for (const line of lines) {
		if (line.startsWith('## Operator Categories')) { inCategories = true; continue }
		if (inCategories && line.startsWith('## ')) { inCategories = false }
		if (!inCategories) continue
		if (line.startsWith('### ')) {
			currentCategory = line.replace(/^###\s+/, '').trim()
		}
		const match = line.match(opRegex)
		if (match) {
			operators.push({
				name:        match[1],
				description: match[2].replace(/\*\*/g, '').trim(),
				category:    currentCategory,
			})
		}
	}

	// Examples: code blocks under ## Common Patterns
	const examples: Array<{ title: string; code: string }> = []
	let inPatterns = false
	let inCode = false
	let currentCode: string[] = []
	let lastH3 = ''

	for (const line of lines) {
		if (line.startsWith('## Common Patterns')) { inPatterns = true; continue }
		if (inPatterns && line.startsWith('## ')) { inPatterns = false }
		if (!inPatterns) continue
		if (line.startsWith('### ')) { lastH3 = line.replace(/^###\s+/, '').trim() }
		if (line.startsWith('```typescript') || line.startsWith('```ts')) {
			inCode = true; currentCode = []; continue
		}
		if (inCode && line.startsWith('```')) {
			examples.push({ title: lastH3, code: currentCode.join('\n') })
			inCode = false; continue
		}
		if (inCode) currentCode.push(line)
	}

	return { description, operators, examples }
}

function categoryToTags(category: string): string[] {
	return category
		.toLowerCase()
		.replace(/[^a-z0-9\s]/g, '')
		.split(/\s+/)
		.filter(Boolean)
}

function familyToFilename(family: string): string {
	// CamelCase → kebab-case
	return family
		.replace(/([a-z])([A-Z])/g, '$1-$2')
		.toLowerCase()
}

// ── Run migration ──────────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true })

const indexImports: string[] = []
const indexExportParts: string[] = []
const allFamilyNames: string[] = []

for (const [filename, family] of Object.entries(FILE_TO_FAMILY)) {
	const filePath = path.join(SOURCE_DIR, filename)
	if (!fs.existsSync(filePath)) {
		console.warn(`SKIP (not found): ${filePath}`)
		continue
	}

	const content = fs.readFileSync(filePath, 'utf-8')
	const parsed  = parseFamilyFile(content)
	const outFile = path.join(OUT_DIR, familyToFilename(family) + '.ts')
	const varName = family.charAt(0).toLowerCase() + family.slice(1) + 'Operators'

	const operatorsTs = parsed.operators.map(op => {
		const examples = parsed.examples.slice(0, 2).map(e =>
			`\t\t{ title: ${JSON.stringify(e.title)}, content: ${JSON.stringify(e.code)} }`
		).join(',\n')
		return `\t{
\t\tname:        ${JSON.stringify(op.name)},
\t\tcategory:    '${family}' as const,
\t\tdefinition:  '',
\t\tdescription: ${JSON.stringify(op.description)},
\t\tvisual:      '',
\t\texamples:    [\n${examples}\n\t\t],
\t\tseeAlso:     [],
\t\ttags:        ${JSON.stringify(categoryToTags(op.category))},
\t}`
	}).join(',\n')

	const ts = `// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const ${varName}: Topic[] = [
${operatorsTs}
]
`
	fs.writeFileSync(outFile, ts)
	console.log(`Written: ${path.basename(outFile)} (${parsed.operators.length} operators)`)

	allFamilyNames.push(family)
	indexImports.push(`import { ${varName} } from './data/${familyToFilename(family)}'`)
	indexExportParts.push(`\t...${varName},`)
}

const indexContent = `// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic, Family } from './types'
${indexImports.join('\n')}

export const operators: Topic[] = [
${indexExportParts.join('\n')}
]

export const families: Family[] = operators.reduce<Family[]>((acc, op) => {
\tconst existing = acc.find(f => f.name === op.category)
\tif (existing) { existing.operators.push(op) }
\telse acc.push({ name: op.category, description: '', operators: [op] })
\treturn acc
}, [])
`

fs.writeFileSync(
	path.join(process.cwd(), 'src/curriculum/index.ts'),
	indexContent
)

console.log(`\nDone. ${allFamilyNames.length} families written.`)
console.log(`Total operators: ${allFamilyNames.length} families`)
