// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const combinationOperators: Topic[] = [
	{
		name:        "merge",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens multiple Observables into one by blending their emissions",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["basic","combination"],
	},
	{
		name:        "concat",
		category:      'Combination' as const,
		definition:   '',
		description: "Emits values from each Observable sequentially, one after another",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["basic","combination"],
	},
	{
		name:        "race",
		category:      'Combination' as const,
		definition:   '',
		description: "Emits values from the first Observable to emit, unsubscribing from others",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["basic","combination"],
	},
	{
		name:        "forkJoin",
		category:      'Combination' as const,
		definition:   '',
		description: "Waits for all Observables to complete, then emits final values as an array",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["basic","combination"],
	},
	{
		name:        "combineLatest",
		category:      'Combination' as const,
		definition:   '',
		description: "Combines latest values from all Observables whenever any emits",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["value","coordination"],
	},
	{
		name:        "combineLatestAll",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens higher-order Observable using combineLatest strategy",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["value","coordination"],
	},
	{
		name:        "withLatestFrom",
		category:      'Combination' as const,
		definition:   '',
		description: "Combines source with latest values from other Observables",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["value","coordination"],
	},
	{
		name:        "zip",
		category:      'Combination' as const,
		definition:   '',
		description: "Combines values from Observables in strict sequential pairs",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["value","coordination"],
	},
	{
		name:        "mergeAll",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens higher-order Observable by merging inner Observables",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["higherorder","flattening"],
	},
	{
		name:        "concatAll",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens higher-order Observable by concatenating inner Observables",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["higherorder","flattening"],
	},
	{
		name:        "switchAll",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens higher-order Observable by switching to latest inner Observable",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["higherorder","flattening"],
	},
	{
		name:        "exhaust",
		category:      'Combination' as const,
		definition:   '',
		description: "Flattens higher-order Observable by ignoring new inner Observables while one is active",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["higherorder","flattening"],
	},
	{
		name:        "startWith",
		category:      'Combination' as const,
		definition:   '',
		description: "Prepends specified values before the source begins emitting",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["joining","patterns"],
	},
	{
		name:        "endWith",
		category:      'Combination' as const,
		definition:   '',
		description: "Appends specified values after the source completes",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["joining","patterns"],
	},
	{
		name:        "pairwise",
		category:      'Combination' as const,
		definition:   '',
		description: "Groups consecutive emissions into pairs [previous, current]",
		visual:      '',
		examples:    [
		{ title: "Merging Multiple Streams", content: "import { merge, interval } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst first$ = interval(1000).pipe(map(x => `First: ${x}`));\nconst second$ = interval(1500).pipe(map(x => `Second: ${x}`));\n\nmerge(first$, second$).subscribe(console.log);\n// Output: First: 0, Second: 0, First: 1, First: 2, Second: 1..." },
		{ title: "Sequential Concatenation", content: "import { concat, of } from 'rxjs';\nimport { delay } from 'rxjs/operators';\n\nconst first$ = of(1, 2, 3);\nconst second$ = of(4, 5, 6).pipe(delay(1000));\nconst third$ = of(7, 8, 9);\n\nconcat(first$, second$, third$).subscribe(console.log);\n// Output: 1, 2, 3, (wait 1s), 4, 5, 6, 7, 8, 9" }
		],
		seeAlso:     [],
		tags:        ["joining","patterns"],
	}
]
