// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const concurrencyOperators: Topic[] = [
	{
		name:        "observeOn",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Controls the scheduler for downstream operators and subscription",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["scheduler","control"],
	},
	{
		name:        "subscribeOn",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Controls the scheduler for the Observable's subscription and unsubscription",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["scheduler","control"],
	},
	{
		name:        "mergeMap",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Flattens with configurable concurrency limit",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["parallel","execution"],
	},
	{
		name:        "concatMap",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Sequential execution (concurrency of 1)",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["parallel","execution"],
	},
	{
		name:        "switchMap",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Cancellation-based concurrency (only latest inner subscription)",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["parallel","execution"],
	},
	{
		name:        "exhaustMap",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Ignores new while busy (prevents concurrent inner subscriptions)",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["parallel","execution"],
	},
	{
		name:        "mergeAll",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Flattens with max concurrent subscriptions",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["concurrency","limiting"],
	},
	{
		name:        "concatAll",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Subscribes to inner Observables sequentially",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["concurrency","limiting"],
	},
	{
		name:        "switchAll",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Switches to latest, canceling previous",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["concurrency","limiting"],
	},
	{
		name:        "exhaust",
		category:      'Concurrency' as const,
		definition:   '',
		description: "Ignores new inner Observables while one is active",
		visual:      '',
		examples:    [
		{ title: "Controlling Subscription Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { subscribeOn, tap } from 'rxjs/operators';\n\nconsole.log('Before subscription');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Value:', x)),\n  subscribeOn(asyncScheduler) // Defer subscription to async context\n).subscribe();\n\nconsole.log('After subscription call');\n\n// Output:\n// Before subscription\n// After subscription call\n// Value: 1\n// Value: 2\n// Value: 3" },
		{ title: "Controlling Notification Context", content: "import { of, asyncScheduler } from 'rxjs';\nimport { observeOn, tap } from 'rxjs/operators';\n\nconsole.log('Start');\n\nof(1, 2, 3).pipe(\n  tap(x => console.log('Before observeOn:', x)),\n  observeOn(asyncScheduler), // Move emissions to async context\n  tap(x => console.log('After observeOn:', x))\n).subscribe();\n\nconsole.log('End');\n\n// Output:\n// Start\n// Before observeOn: 1\n// Before observeOn: 2\n// Before observeOn: 3\n// End\n// After observeOn: 1\n// After observeOn: 2\n// After observeOn: 3" }
		],
		seeAlso:     [],
		tags:        ["concurrency","limiting"],
	}
]
