// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types.ts'

export const conditionalOperators: Operator[] = [
	{
		name:        "every",
		family:      'Conditional' as const,
		signature:   '',
		description: "Tests if all emitted values satisfy a predicate",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["value","testing"],
	},
	{
		name:        "find",
		family:      'Conditional' as const,
		signature:   '',
		description: "Emits the first value that satisfies a predicate, then completes",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["value","testing"],
	},
	{
		name:        "findIndex",
		family:      'Conditional' as const,
		signature:   '',
		description: "Emits the index of the first value satisfying a predicate",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["value","testing"],
	},
	{
		name:        "isEmpty",
		family:      'Conditional' as const,
		signature:   '',
		description: "Emits true if source completes without emitting, false otherwise",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["value","testing"],
	},
	{
		name:        "defaultIfEmpty",
		family:      'Conditional' as const,
		signature:   '',
		description: "Emits a default value if the source completes without emitting",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["stream","selection"],
	},
	{
		name:        "iif",
		family:      'Conditional' as const,
		signature:   '',
		description: "Subscribes to one of two Observables based on a condition evaluated at subscription time",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["stream","selection"],
	},
	{
		name:        "throwIfEmpty",
		family:      'Conditional' as const,
		signature:   '',
		description: "Throws an error if the source completes without emitting any values",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["stream","selection"],
	},
	{
		name:        "sequenceEqual",
		family:      'Conditional' as const,
		signature:   '',
		description: "Compares two Observables to see if they emit the same sequence",
		marble:      '',
		examples:    [
		{ title: "Testing All Values with Every", code: "import { of } from 'rxjs';\nimport { every } from 'rxjs/operators';\n\nof(2, 4, 6, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? true\n\nof(2, 4, 5, 8, 10).pipe(\n  every(x => x % 2 === 0)\n).subscribe(result => console.log('All even?', result));\n// Output: All even? false" },
		{ title: "Finding First Match", code: "import { of } from 'rxjs';\nimport { find, findIndex } from 'rxjs/operators';\n\nconst numbers$ = of(1, 2, 3, 4, 5);\n\n// Find first value > 3\nnumbers$.pipe(\n  find(x => x > 3)\n).subscribe(value => console.log('Found:', value));\n// Output: Found: 4\n\n// Find index of first value > 3\nnumbers$.pipe(\n  findIndex(x => x > 3)\n).subscribe(index => console.log('Found at index:', index));\n// Output: Found at index: 3" }
		],
		seeAlso:     [],
		tags:        ["comparative","operations"],
	}
]
