// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const creationOperators: Topic[] = [
	{
		name:        "of",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that emits a sequence of provided values synchronously",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["from","existing","sources"],
	},
	{
		name:        "from",
		category:    'Creation' as const,
		definition:  '',
		description: "Converts various data sources (arrays, promises, iterables) into Observables",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["from","existing","sources"],
	},
	{
		name:        "fromEvent",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable from DOM events or Node.js EventEmitter events",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["from","existing","sources"],
	},
	{
		name:        "fromEventPattern",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable from an arbitrary API for registering event handlers",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["from","existing","sources"],
	},
	{
		name:        "range",
		category:    'Creation' as const,
		definition:  '',
		description: "Emits a sequence of numbers within a specified range",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["value","generation"],
	},
	{
		name:        "generate",
		category:    'Creation' as const,
		definition:  '',
		description: "Generates values using a loop similar to a traditional for loop",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["value","generation"],
	},
	{
		name:        "interval",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that emits sequential numbers at specified time intervals",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["value","generation"],
	},
	{
		name:        "timer",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that emits after a delay and optionally at regular intervals",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["value","generation"],
	},
	{
		name:        "defer",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable only when subscribed to, deferring creation logic",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["advanced","creation"],
	},
	{
		name:        "ajax",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable for Ajax HTTP requests",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["advanced","creation"],
	},
	{
		name:        "empty",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that immediately completes",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["advanced","creation"],
	},
	{
		name:        "throwError",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that immediately emits an error",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["advanced","creation"],
	},
	{
		name:        "never",
		category:    'Creation' as const,
		definition:  '',
		description: "Creates an Observable that never emits values or completes",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["advanced","creation"],
	},
	{
		name:        "Observable.create",
		category:    'Creation' as const,
		definition:  '',
		description: "/ new Observable(): Creates a custom Observable with complete control over emissions",
		visual:      '',
		examples:    [
		{ title: "Converting Arrays to Streams", content: "import { from, of } from 'rxjs';\n\n// Emit array items individually\nfrom([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: 1, 2, 3, 4, 5\n\n// Emit entire array as single emission\nof([1, 2, 3, 4, 5]).subscribe(console.log);\n// Output: [1, 2, 3, 4, 5]" },
		{ title: "Event Stream Creation", content: "import { fromEvent } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nconst button = document.querySelector('button');\nconst clicks$ = fromEvent(button, 'click').pipe(\n  map(event => ({ x: event.clientX, y: event.clientY }))\n);\n\nclicks$.subscribe(coords => console.log(coords));" }
		],
		seeAlso:     [],
		tags:        ["custom","creation"],
	}
]
