// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const errorHandlingOperators: Topic[] = [
	{
		name:        "catchError",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Catches errors and returns a new Observable or throws a new error",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","recovery"],
	},
	{
		name:        "onErrorResumeNext",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Continues with next Observable when an error occurs, ignoring the error",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","recovery"],
	},
	{
		name:        "retry",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Resubscribes to source Observable on error, with optional count",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["retry","strategies"],
	},
	{
		name:        "retryWhen",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Resubscribes based on custom logic using a notifier Observable",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["retry","strategies"],
	},
	{
		name:        "finalize",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Executes a callback when Observable completes or errors (cleanup)",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","finalization"],
	},
	{
		name:        "tap",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Performs side effects for errors without affecting the stream",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","finalization"],
	},
	{
		name:        "throwError",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Creates an Observable that immediately emits an error",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","creation"],
	},
	{
		name:        "throwIfEmpty",
		category:      'ErrorHandling' as const,
		definition:   '',
		description: "Emits error if source completes without emitting any values",
		visual:      '',
		examples:    [
		{ title: "Basic Error Catching", content: "import { of, throwError } from 'rxjs';\nimport { catchError, map } from 'rxjs/operators';\n\nconst source$ = throwError(() => new Error('Something went wrong!'));\n\nsource$.pipe(\n  catchError(error => {\n    console.error('Caught error:', error.message);\n    return of('Fallback value');\n  })\n).subscribe(\n  value => console.log('Value:', value),\n  error => console.error('Error:', error)\n);\n// Output: Caught error: Something went wrong!\n//         Value: Fallback value" },
		{ title: "HTTP Request with Fallback", content: "import { ajax } from 'rxjs/ajax';\nimport { catchError, of } from 'rxjs';\n\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  catchError(error => {\n    console.error('API call failed:', error);\n    // Return cached or default data\n    return of({ name: 'Guest', id: null });\n  })\n);\n\nuserData$.subscribe(user => console.log('User:', user));" }
		],
		seeAlso:     [],
		tags:        ["error","creation"],
	}
]
