// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const filteringOperators: Operator[] = [
	{
		name:        "filter",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only values that satisfy a predicate function",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["conditional","filtering"],
	},
	{
		name:        "first",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only the first value (or first matching a predicate), then completes",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["conditional","filtering"],
	},
	{
		name:        "last",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only the last value (or last matching a predicate), then completes",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["conditional","filtering"],
	},
	{
		name:        "find",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits the first value matching a predicate, then completes",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["conditional","filtering"],
	},
	{
		name:        "single",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only if exactly one value is emitted, errors otherwise",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["conditional","filtering"],
	},
	{
		name:        "take",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only the first N values",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "takeLast",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only the last N values",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "takeUntil",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits until a notifier Observable emits",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "takeWhile",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits while a predicate is true",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "skip",
		family:      'Filtering' as const,
		signature:   '',
		description: "Skips the first N values",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "skipLast",
		family:      'Filtering' as const,
		signature:   '',
		description: "Skips the last N values",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "skipUntil",
		family:      'Filtering' as const,
		signature:   '',
		description: "Skips until a notifier Observable emits",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "skipWhile",
		family:      'Filtering' as const,
		signature:   '',
		description: "Skips while a predicate is true",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "elementAt",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only the value at a specific index",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["positional","filtering"],
	},
	{
		name:        "distinct",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only values that have never been emitted before",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["distinctness","filtering"],
	},
	{
		name:        "distinctUntilChanged",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only when the current value differs from the previous",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["distinctness","filtering"],
	},
	{
		name:        "distinctUntilKeyChanged",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits only when a specified key's value differs from previous",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["distinctness","filtering"],
	},
	{
		name:        "debounce",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits after a specified time span determined by another Observable",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "debounceTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits after a specified time span of silence",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "throttle",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits, then ignores values for a time span determined by another Observable",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "throttleTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits, then ignores values for a specified time span",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "audit",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits the most recent value after a time span determined by another Observable",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "auditTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits the most recent value after a specified time span",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "sample",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits the most recent value when a notifier Observable emits",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "sampleTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits the most recent value at periodic time intervals",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["timebased","filtering"],
	},
	{
		name:        "sample",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits most recent source value whenever notifier emits",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["sampling","and","auditing"],
	},
	{
		name:        "sampleTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Emits most recent source value at periodic intervals",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["sampling","and","auditing"],
	},
	{
		name:        "audit",
		family:      'Filtering' as const,
		signature:   '',
		description: "Ignores source values, emits most recent after duration from another Observable",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["sampling","and","auditing"],
	},
	{
		name:        "auditTime",
		family:      'Filtering' as const,
		signature:   '',
		description: "Ignores source values, emits most recent after time period",
		marble:      '',
		examples:    [
		{ title: "Predicate-Based Filtering", code: "import { of } from 'rxjs';\nimport { filter } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5, 6).pipe(\n  filter(x => x % 2 === 0)\n).subscribe(console.log);\n// Output: 2, 4, 6" },
		{ title: "Taking and Skipping", code: "import { interval } from 'rxjs';\nimport { take, skip, takeLast } from 'rxjs/operators';\n\nconst numbers$ = interval(100);\n\n// Take first 5 values\nnumbers$.pipe(take(5)).subscribe(console.log);\n// Output: 0, 1, 2, 3, 4\n\n// Skip first 3, then take 3\nnumbers$.pipe(\n  skip(3),\n  take(3)\n).subscribe(console.log);\n// Output: 3, 4, 5" }
		],
		seeAlso:     [],
		tags:        ["sampling","and","auditing"],
	}
]
