// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const inspectionOperators: Topic[] = [
	{
		name:        "tap",
		category:    'Inspection' as const,
		definition:  '',
		description: "Performs side effects for notifications (next, error, complete) without affecting stream",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["core","inspection"],
	},
	{
		name:        "tap",
		category:    'Inspection' as const,
		definition:  '',
		description: "Separate handlers for next, error, and complete",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["core","inspection"],
	},
	{
		name:        "finalize",
		category:    'Inspection' as const,
		definition:  '',
		description: "Executes callback when Observable completes, errors, or is unsubscribed",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["core","inspection"],
	},
	{
		name:        "timeInterval",
		category:    'Inspection' as const,
		definition:  '',
		description: "Wraps each emission with time elapsed since previous emission",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["timing","inspection"],
	},
	{
		name:        "timestamp",
		category:    'Inspection' as const,
		definition:  '',
		description: "Wraps each emission with current timestamp",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["timing","inspection"],
	},
	{
		name:        "delay",
		category:    'Inspection' as const,
		definition:  '',
		description: "Delays emissions (useful for observing timing)",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["timing","inspection"],
	},
	{
		name:        "materialize",
		category:    'Inspection' as const,
		definition:  '',
		description: "Converts emissions into Notification objects for inspection",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["notification","inspection"],
	},
	{
		name:        "dematerialize",
		category:    'Inspection' as const,
		definition:  '',
		description: "Converts Notification objects back to normal emissions",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["notification","inspection"],
	},
	{
		name:        "tap",
		category:    'Inspection' as const,
		definition:  '',
		description: "Log values, errors, and completion",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["debugging","utilities"],
	},
	{
		name:        "tap",
		category:    'Inspection' as const,
		definition:  '',
		description: "Inspect values during debugging",
		visual:      '',
		examples:    [
		{ title: "Basic Side Effects with Tap", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 2),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 2\n// Final: 2\n// Before map: 2\n// After map: 4\n// Final: 4\n// ..." },
		{ title: "Tap with Observer Object", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  map(x => {\n    if (x === 2) throw new Error('Error at 2');\n    return x * 10;\n  }),\n  tap({\n    next: value => console.log('Value:', value),\n    error: error => console.error('Error caught:', error.message),\n    complete: () => console.log('Stream completed')\n  })\n).subscribe({\n  next: value => console.log('Subscriber received:', value),\n  error: error => console.error('Subscriber error:', error.message)\n});\n\n// Output:\n// Value: 10\n// Subscriber received: 10\n// Error caught: Error at 2\n// Subscriber error: Error at 2" }
		],
		seeAlso:     [],
		tags:        ["debugging","utilities"],
	}
]
