// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const joinCreationOperators: Operator[] = [
	{
		name:        "buffer",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Collects source values into arrays, emitted when notifier Observable emits",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["buffering","joins"],
	},
	{
		name:        "bufferToggle",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Buffers using opening Observable and closing Observable factory",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["buffering","joins"],
	},
	{
		name:        "bufferWhen",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Buffers using closing selector function",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["buffering","joins"],
	},
	{
		name:        "bufferCount",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Buffers a specified number of values",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["buffering","joins"],
	},
	{
		name:        "bufferTime",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Buffers values for a specified time duration",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["buffering","joins"],
	},
	{
		name:        "window",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Groups source values into nested Observables based on notifier",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["windowing","joins"],
	},
	{
		name:        "windowToggle",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Windows using opening Observable and closing Observable factory",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["windowing","joins"],
	},
	{
		name:        "windowWhen",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Windows using closing selector function",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["windowing","joins"],
	},
	{
		name:        "windowCount",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Groups values into nested Observables of specified count",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["windowing","joins"],
	},
	{
		name:        "windowTime",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Groups values into nested Observables over time duration",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["windowing","joins"],
	},
	{
		name:        "combineLatestWith",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Combines with other Observables, emitting arrays on any source emission",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["complex","joins"],
	},
	{
		name:        "zipWith",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Combines with other Observables in strict sequential pairs",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["complex","joins"],
	},
	{
		name:        "mergeWith",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Merges with other Observables concurrently",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["complex","joins"],
	},
	{
		name:        "concatWith",
		family:      'JoinCreation' as const,
		signature:   '',
		description: "Concatenates with other Observables sequentially",
		marble:      '',
		examples:    [
		{ title: "Buffer with Notifier", code: "import { interval, fromEvent } from 'rxjs';\nimport { buffer } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst clicks$ = fromEvent(document, 'click');\n\nsource$.pipe(\n  buffer(clicks$)  // Buffer values until click\n).subscribe(buffered => {\n  console.log('Buffered values:', buffered);\n});\n// Output: Buffered values: [0, 1, 2, 3, 4] (on click)\n//         Buffered values: [5, 6, 7] (on next click)" },
		{ title: "BufferToggle for Dynamic Buffering", code: "import { interval, fromEvent } from 'rxjs';\nimport { bufferToggle, map } from 'rxjs/operators';\n\nconst source$ = interval(100);\nconst startBuffer$ = fromEvent(document, 'mousedown');\nconst stopBuffer$ = fromEvent(document, 'mouseup');\n\nsource$.pipe(\n  bufferToggle(\n    startBuffer$,\n    () => stopBuffer$  // Factory function for closing Observable\n  )\n).subscribe(buffered => {\n  console.log('Captured during mouse press:', buffered);\n});\n// Buffers values only while mouse is pressed" }
		],
		seeAlso:     [],
		tags:        ["complex","joins"],
	}
]
