// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const mathematicalOperators: Operator[] = [
	{
		name:        "count",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Counts the number of emissions and emits the total when source completes",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["basic","aggregation"],
	},
	{
		name:        "max",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Emits the maximum value when source completes",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["basic","aggregation"],
	},
	{
		name:        "min",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Emits the minimum value when source completes",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["basic","aggregation"],
	},
	{
		name:        "reduce",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Applies accumulator function and emits final result when source completes",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["basic","aggregation"],
	},
	{
		name:        "sum",
		family:      'Mathematical' as const,
		signature:   '',
		description: "(Custom) Calculates sum of all numeric emissions",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["numeric","operations"],
	},
	{
		name:        "average",
		family:      'Mathematical' as const,
		signature:   '',
		description: "(Custom) Calculates average of all numeric emissions",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["numeric","operations"],
	},
	{
		name:        "max",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Finds maximum using custom comparison function",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["comparative","operations"],
	},
	{
		name:        "min",
		family:      'Mathematical' as const,
		signature:   '',
		description: "Finds minimum using custom comparison function",
		marble:      '',
		examples:    [
		{ title: "Counting Emissions", code: "import { of, range } from 'rxjs';\nimport { count } from 'rxjs/operators';\n\n// Count all emissions\nrange(1, 10).pipe(\n  count()\n).subscribe(total => console.log('Total count:', total));\n// Output: Total count: 10\n\n// Count with predicate\nrange(1, 10).pipe(\n  count(x => x % 2 === 0)\n).subscribe(total => console.log('Even numbers:', total));\n// Output: Even numbers: 5" },
		{ title: "Finding Min and Max", code: "import { of } from 'rxjs';\nimport { max, min } from 'rxjs/operators';\n\nconst numbers$ = of(5, 3, 9, 1, 7, 2, 8);\n\nnumbers$.pipe(\n  max()\n).subscribe(result => console.log('Maximum:', result));\n// Output: Maximum: 9\n\nnumbers$.pipe(\n  min()\n).subscribe(result => console.log('Minimum:', result));\n// Output: Minimum: 1" }
		],
		seeAlso:     [],
		tags:        ["comparative","operations"],
	}
]
