// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const multicastingOperators: Operator[] = [
	{
		name:        "share",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Shares source Observable among multiple subscribers using a Subject",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "shareReplay",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Shares and replays specified number of emissions to new subscribers",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "multicast",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Multicasts using a provided Subject or Subject factory",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "publish",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Returns a ConnectableObservable that shares source execution",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "publishReplay",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Returns ConnectableObservable that replays emissions",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "publishLast",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Returns ConnectableObservable that emits only the last value",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "publishBehavior",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Returns ConnectableObservable with an initial value",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["basic","multicasting"],
	},
	{
		name:        "connect",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Manually initiates execution of a ConnectableObservable",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["connectable","observables"],
	},
	{
		name:        "refCount",
		family:      'Multicasting' as const,
		signature:   '',
		description: "Automatically manages connections based on subscriber count",
		marble:      '',
		examples:    [
		{ title: "Basic Sharing", code: "import { interval } from 'rxjs';\nimport { share, take, tap } from 'rxjs/operators';\n\nconst source$ = interval(1000).pipe(\n  take(5),\n  tap(x => console.log('Source execution:', x)),\n  share() // Share single execution\n);\n\n// Both subscribers share the same execution\nsource$.subscribe(x => console.log('Subscriber A:', x));\nsetTimeout(() => {\n  source$.subscribe(x => console.log('Subscriber B:', x));\n}, 2000);\n\n// Output shows single execution shared by both subscribers" },
		{ title: "ShareReplay for Caching", code: "import { ajax } from 'rxjs/ajax';\nimport { shareReplay } from 'rxjs/operators';\n\n// Cache API response and replay to all subscribers\nconst userData$ = ajax.getJSON('/api/user').pipe(\n  shareReplay(1) // Replay last emission to new subscribers\n);\n\n// First subscriber triggers HTTP request\nuserData$.subscribe(user => console.log('First:', user));\n\n// Late subscriber receives cached result (no new request)\nsetTimeout(() => {\n  userData$.subscribe(user => console.log('Second:', user));\n}, 5000);" }
		],
		seeAlso:     [],
		tags:        ["connectable","observables"],
	}
]
