// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const rateLimitingOperators: Operator[] = [
	{
		name:        "throttle",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits, then ignores values for a duration determined by another Observable",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["timebased","throttling"],
	},
	{
		name:        "throttleTime",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits, then ignores values for a specified time duration",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["timebased","throttling"],
	},
	{
		name:        "auditTime",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Ignores values, then emits the most recent after a time period",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["timebased","throttling"],
	},
	{
		name:        "audit",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Ignores values, then emits most recent after duration from another Observable",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["timebased","throttling"],
	},
	{
		name:        "debounce",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits after a silence period determined by another Observable",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["debouncing"],
	},
	{
		name:        "debounceTime",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits after a specified silence period (no emissions)",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["debouncing"],
	},
	{
		name:        "sample",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits the most recent value when a notifier Observable emits",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["sampling"],
	},
	{
		name:        "sampleTime",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Emits the most recent value at periodic time intervals",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["sampling"],
	},
	{
		name:        "throttleTime",
		family:      'RateLimiting' as const,
		signature:   '',
		description: "Advanced throttling with leading/trailing edge control",
		marble:      '',
		examples:    [
		{ title: "Basic Throttling", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst mousemove$ = fromEvent(document, 'mousemove');\n\nmousemove$.pipe(\n  throttleTime(100) // Emit at most once per 100ms\n).subscribe(event => {\n  console.log('Mouse position:', event.clientX, event.clientY);\n});\n\n// Instead of 1000s of events per second, emits max 10/second" },
		{ title: "Throttle with Leading and Trailing", code: "import { fromEvent } from 'rxjs';\nimport { throttleTime } from 'rxjs/operators';\n\nconst button = document.querySelector('#submit') as HTMLButtonElement;\n\nfromEvent(button, 'click').pipe(\n  throttleTime(2000, undefined, { \n    leading: true,   // Emit immediately on first click\n    trailing: true   // Emit again if clicked during cooldown\n  })\n).subscribe(() => {\n  console.log('Button clicked (throttled)');\n});" }
		],
		seeAlso:     [],
		tags:        ["rate","control"],
	}
]
