// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const singleValueOperators: Topic[] = [
	{
		name:        "first",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits only the first value (or first matching a predicate), then completes",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["positional","selection"],
	},
	{
		name:        "last",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits only the last value (or last matching a predicate) when source completes",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["positional","selection"],
	},
	{
		name:        "elementAt",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits the value at a specified index position",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["positional","selection"],
	},
	{
		name:        "find",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits the first value that satisfies a predicate, then completes",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["conditional","selection"],
	},
	{
		name:        "single",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits only if exactly one value is emitted; errors if zero or multiple values",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["conditional","selection"],
	},
	{
		name:        "first",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits default if stream completes without matching value",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["default","handling"],
	},
	{
		name:        "last",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits default if stream completes without matching value",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["default","handling"],
	},
	{
		name:        "elementAt",
		category:      'SingleValue' as const,
		definition:   '',
		description: "Emits default if index is out of bounds",
		visual:      '',
		examples:    [
		{ title: "Getting First Value", content: "import { of, EMPTY } from 'rxjs';\nimport { first } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  first()\n).subscribe(console.log);\n// Output: 1\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  first(x => x > 3)\n).subscribe(console.log);\n// Output: 4\n\n// With default value\nEMPTY.pipe(\n  first(undefined, 'default')\n).subscribe(console.log);\n// Output: 'default'" },
		{ title: "Getting Last Value", content: "import { of, EMPTY } from 'rxjs';\nimport { last } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  last()\n).subscribe(console.log);\n// Output: 5\n\n// With predicate\nof(1, 2, 3, 4, 5).pipe(\n  last(x => x < 4)\n).subscribe(console.log);\n// Output: 3\n\n// With default value\nEMPTY.pipe(\n  last(undefined, 'no values')\n).subscribe(console.log);\n// Output: 'no values'" }
		],
		seeAlso:     [],
		tags:        ["default","handling"],
	}
]
