// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types'

export const testingOperators: Operator[] = [
	{
		name:        "TestScheduler",
		family:      'Testing' as const,
		signature:   '',
		description: "Virtual time scheduler for testing without real delays",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","schedulers"],
	},
	{
		name:        "VirtualTimeScheduler",
		family:      'Testing' as const,
		signature:   '',
		description: "Alternative virtual time implementation",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","schedulers"],
	},
	{
		name:        "AnimationFrameScheduler",
		family:      'Testing' as const,
		signature:   '',
		description: "For testing animation-related streams",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","schedulers"],
	},
	{
		name:        "expectObservable",
		family:      'Testing' as const,
		signature:   '',
		description: "Assert Observable emissions match marble diagram",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","utilities"],
	},
	{
		name:        "expectSubscriptions",
		family:      'Testing' as const,
		signature:   '',
		description: "Verify subscription timing",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","utilities"],
	},
	{
		name:        "hot",
		family:      'Testing' as const,
		signature:   '',
		description: "Create hot Observable from marble diagram",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","utilities"],
	},
	{
		name:        "cold",
		family:      'Testing' as const,
		signature:   '',
		description: "Create cold Observable from marble diagram",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","utilities"],
	},
	{
		name:        "flush",
		family:      'Testing' as const,
		signature:   '',
		description: "Trigger all scheduled actions",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["test","utilities"],
	},
	{
		name:        "delay",
		family:      'Testing' as const,
		signature:   '',
		description: "Test timing with virtual time",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["helper","operators"],
	},
	{
		name:        "timeout",
		family:      'Testing' as const,
		signature:   '',
		description: "Test timeout scenarios",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["helper","operators"],
	},
	{
		name:        "timeInterval",
		family:      'Testing' as const,
		signature:   '',
		description: "Verify emission intervals",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["helper","operators"],
	},
	{
		name:        "timestamp",
		family:      'Testing' as const,
		signature:   '',
		description: "Verify emission timestamps",
		marble:      '',
		examples:    [
		{ title: "Basic Marble Testing", code: "import { TestScheduler } from 'rxjs/testing';\nimport { map } from 'rxjs/operators';\n\ndescribe('Observable tests', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should map values', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    a-b-c|';\n      const result$ = source$.pipe(map(x => x * 10));\n      \n      expectObservable(result$).toBe(expected, { a: 10, b: 20, c: 30 });\n    });\n  });\n});" },
		{ title: "Testing Async Operations", code: "import { TestScheduler } from 'rxjs/testing';\nimport { delay, map } from 'rxjs/operators';\n\ndescribe('Async operations', () => {\n  let testScheduler: TestScheduler;\n\n  beforeEach(() => {\n    testScheduler = new TestScheduler((actual, expected) => {\n      expect(actual).toEqual(expected);\n    });\n  });\n\n  it('should delay emissions', () => {\n    testScheduler.run(({ cold, expectObservable }) => {\n      const source$ = cold('a-b-c|', { a: 1, b: 2, c: 3 });\n      const expected = '    ---a-b-c|'; // 30ms delay (3 frames)\n      const result$ = source$.pipe(delay(30));\n      \n      expectObservable(result$).toBe(expected, { a: 1, b: 2, c: 3 });\n    });\n  });\n});" }
		],
		seeAlso:     [],
		tags:        ["helper","operators"],
	}
]
