// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const timingOperators: Topic[] = [
	{
		name:        "delay",
		category:      'Timing' as const,
		definition:   '',
		description: "Delays emission of all values by a specified time",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["delaying","operations"],
	},
	{
		name:        "delayWhen",
		category:      'Timing' as const,
		definition:   '',
		description: "Delays emissions by a duration determined by another Observable",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["delaying","operations"],
	},
	{
		name:        "timeout",
		category:      'Timing' as const,
		definition:   '',
		description: "Errors if Observable doesn't emit within specified time",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["timeout","management"],
	},
	{
		name:        "timeoutWith",
		category:      'Timing' as const,
		definition:   '',
		description: "Switches to fallback Observable on timeout",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["timeout","management"],
	},
	{
		name:        "timeInterval",
		category:      'Timing' as const,
		definition:   '',
		description: "Wraps each emission with elapsed time since previous emission",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["time","measurement"],
	},
	{
		name:        "timestamp",
		category:      'Timing' as const,
		definition:   '',
		description: "Wraps each emission with current timestamp",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["time","measurement"],
	},
	{
		name:        "subscribeOn",
		category:      'Timing' as const,
		definition:   '',
		description: "Controls scheduler used for subscription",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["scheduler","control"],
	},
	{
		name:        "observeOn",
		category:      'Timing' as const,
		definition:   '',
		description: "Controls scheduler used for emissions",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["scheduler","control"],
	},
	{
		name:        "interval",
		category:      'Timing' as const,
		definition:   '',
		description: "Emits sequential numbers at specified intervals",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["timebased","creation"],
	},
	{
		name:        "timer",
		category:      'Timing' as const,
		definition:   '',
		description: "Emits after delay and optionally at intervals",
		visual:      '',
		examples:    [
		{ title: "Simple Delay", content: "import { of } from 'rxjs';\nimport { delay, tap } from 'rxjs/operators';\n\nconsole.log('Start:', new Date().toISOString());\n\nof(1, 2, 3).pipe(\n  delay(2000),\n  tap(x => console.log('Value:', x, new Date().toISOString()))\n).subscribe();\n\n// Output:\n// Start: 2024-01-15T10:00:00.000Z\n// (2 second delay)\n// Value: 1 2024-01-15T10:00:02.000Z\n// Value: 2 2024-01-15T10:00:02.000Z\n// Value: 3 2024-01-15T10:00:02.000Z" },
		{ title: "Conditional Delay with DelayWhen", content: "import { of, timer } from 'rxjs';\nimport { delayWhen } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  delayWhen(value => timer(value * 1000))\n).subscribe(x => {\n  console.log('Value:', x, 'at', new Date().toISOString());\n});\n\n// Output:\n// Value: 1 at ...T10:00:01.000Z (after 1s)\n// Value: 2 at ...T10:00:02.000Z (after 2s)\n// Value: 3 at ...T10:00:03.000Z (after 3s)\n// Value: 4 at ...T10:00:04.000Z (after 4s)\n// Value: 5 at ...T10:00:05.000Z (after 5s)" }
		],
		seeAlso:     [],
		tags:        ["timebased","creation"],
	}
]
