// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Operator } from '../types.ts'

export const transformationOperators: Operator[] = [
	{
		name:        "map",
		family:      'Transformation' as const,
		signature:   '',
		description: "Applies a projection function to each emitted value",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["basic","mapping"],
	},
	{
		name:        "mapTo",
		family:      'Transformation' as const,
		signature:   '',
		description: "Maps every emission to a constant value",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["basic","mapping"],
	},
	{
		name:        "pluck",
		family:      'Transformation' as const,
		signature:   '',
		description: "Extracts nested property values from objects",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["basic","mapping"],
	},
	{
		name:        "mergeMap",
		family:      'Transformation' as const,
		signature:   '',
		description: "Projects each value to an Observable and flattens all into one stream",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["flattening","operations"],
	},
	{
		name:        "switchMap",
		family:      'Transformation' as const,
		signature:   '',
		description: "Projects to Observable, canceling previous inner subscriptions on new emissions",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["flattening","operations"],
	},
	{
		name:        "concatMap",
		family:      'Transformation' as const,
		signature:   '',
		description: "Projects to Observable, queuing inner subscriptions sequentially",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["flattening","operations"],
	},
	{
		name:        "exhaustMap",
		family:      'Transformation' as const,
		signature:   '',
		description: "Projects to Observable, ignoring new emissions while inner Observable is active",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["flattening","operations"],
	},
	{
		name:        "scan",
		family:      'Transformation' as const,
		signature:   '',
		description: "Accumulates values over time, emitting each intermediate result",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["accumulation"],
	},
	{
		name:        "reduce",
		family:      'Transformation' as const,
		signature:   '',
		description: "Accumulates all values and emits a single final result when source completes",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["accumulation"],
	},
	{
		name:        "expand",
		family:      'Transformation' as const,
		signature:   '',
		description: "Recursively projects each value to an Observable and flattens",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["accumulation"],
	},
	{
		name:        "buffer",
		family:      'Transformation' as const,
		signature:   '',
		description: "Collects values into arrays based on a notifier Observable",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "bufferCount",
		family:      'Transformation' as const,
		signature:   '',
		description: "Collects values into arrays of a specified size",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "bufferTime",
		family:      'Transformation' as const,
		signature:   '',
		description: "Collects values into arrays over time intervals",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "bufferToggle",
		family:      'Transformation' as const,
		signature:   '',
		description: "Collects values using opening and closing Observables",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "bufferWhen",
		family:      'Transformation' as const,
		signature:   '',
		description: "Collects values using a factory function for closing Observables",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "window",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups values into nested Observables based on a notifier",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "windowCount",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups values into nested Observables of a specified size",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "windowTime",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups values into nested Observables over time intervals",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "windowToggle",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups values using opening and closing Observables",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "windowWhen",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups values using a factory function for closing Observables",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["buffering","and","windowing"],
	},
	{
		name:        "mergeScan",
		family:      'Transformation' as const,
		signature:   '',
		description: "Combines scan and mergeMap for stateful async transformations",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["advanced","transformations"],
	},
	{
		name:        "pairwise",
		family:      'Transformation' as const,
		signature:   '',
		description: "Emits the previous and current values as a pair",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["advanced","transformations"],
	},
	{
		name:        "partition",
		family:      'Transformation' as const,
		signature:   '',
		description: "Splits source Observable into two based on a predicate",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["advanced","transformations"],
	},
	{
		name:        "groupBy",
		family:      'Transformation' as const,
		signature:   '',
		description: "Groups emissions by key, creating nested Observables",
		marble:      '',
		examples:    [
		{ title: "Simple Value Transformation", code: "import { of } from 'rxjs';\nimport { map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  map(x => x * 10)\n).subscribe(console.log);\n// Output: 10, 20, 30, 40, 50" },
		{ title: "Flattening Strategies", code: "import { fromEvent, interval } from 'rxjs';\nimport { switchMap, mergeMap, concatMap, exhaustMap, take } from 'rxjs/operators';\n\nconst clicks$ = fromEvent(document, 'click');\n\n// switchMap: Cancel previous, switch to latest\nclicks$.pipe(\n  switchMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each click cancels the previous interval\n\n// mergeMap: Run all concurrently\nclicks$.pipe(\n  mergeMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// All intervals run simultaneously\n\n// concatMap: Queue and run sequentially\nclicks$.pipe(\n  concatMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Each interval waits for previous to complete\n\n// exhaustMap: Ignore new emissions while busy\nclicks$.pipe(\n  exhaustMap(() => interval(1000).pipe(take(3)))\n).subscribe(console.log);\n// Ignores clicks while interval is active" }
		],
		seeAlso:     [],
		tags:        ["advanced","transformations"],
	}
]
