// GENERATED by scripts/migrate-markdown.ts — do not edit manually
import type { Topic } from '../types'

export const utilityOperators: Topic[] = [
	{
		name:        "tap",
		category:      'Utility' as const,
		definition:   '',
		description: "Performs side effects for each emission without affecting the stream",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["debugging","and","inspection"],
	},
	{
		name:        "tap",
		category:      'Utility' as const,
		definition:   '',
		description: "Handles next, error, and complete notifications separately",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["debugging","and","inspection"],
	},
	{
		name:        "delay",
		category:      'Utility' as const,
		definition:   '',
		description: "Delays emission of all values by a specified time",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["timing","control"],
	},
	{
		name:        "delayWhen",
		category:      'Utility' as const,
		definition:   '',
		description: "Delays emissions by a duration determined by another Observable",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["timing","control"],
	},
	{
		name:        "timeout",
		category:      'Utility' as const,
		definition:   '',
		description: "Errors if Observable doesn't emit within specified time",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["timing","control"],
	},
	{
		name:        "timeInterval",
		category:      'Utility' as const,
		definition:   '',
		description: "Emits time elapsed between consecutive emissions",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["timing","control"],
	},
	{
		name:        "timestamp",
		category:      'Utility' as const,
		definition:   '',
		description: "Wraps each value with a timestamp",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["timing","control"],
	},
	{
		name:        "subscribeOn",
		category:      'Utility' as const,
		definition:   '',
		description: "Controls which scheduler is used when subscribing",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["subscription","management"],
	},
	{
		name:        "observeOn",
		category:      'Utility' as const,
		definition:   '',
		description: "Controls which scheduler is used for emitting notifications",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["subscription","management"],
	},
	{
		name:        "repeat",
		category:      'Utility' as const,
		definition:   '',
		description: "Resubscribes to source Observable a specified number of times",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["subscription","management"],
	},
	{
		name:        "repeatWhen",
		category:      'Utility' as const,
		definition:   '',
		description: "Resubscribes based on custom logic using a notifier Observable",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["subscription","management"],
	},
	{
		name:        "materialize",
		category:      'Utility' as const,
		definition:   '',
		description: "Converts Observable emissions into Notification objects",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["notification","handling"],
	},
	{
		name:        "dematerialize",
		category:      'Utility' as const,
		definition:   '',
		description: "Converts Notification objects back into emissions",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["notification","handling"],
	},
	{
		name:        "toArray",
		category:      'Utility' as const,
		definition:   '',
		description: "Collects all emissions into an array, emitted when source completes",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["notification","handling"],
	},
	{
		name:        "finalize",
		category:      'Utility' as const,
		definition:   '',
		description: "Executes callback when Observable completes, errors, or is unsubscribed",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["connection","and","finalization"],
	},
	{
		name:        "connect",
		category:      'Utility' as const,
		definition:   '',
		description: "Manually starts execution of a ConnectableObservable",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["connection","and","finalization"],
	},
	{
		name:        "defaultIfEmpty",
		category:      'Utility' as const,
		definition:   '',
		description: "Emits a default value if source completes without emitting",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["advanced","utilities"],
	},
	{
		name:        "every",
		category:      'Utility' as const,
		definition:   '',
		description: "Emits true/false based on whether all values satisfy a predicate",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["advanced","utilities"],
	},
	{
		name:        "isEmpty",
		category:      'Utility' as const,
		definition:   '',
		description: "Emits true if source completes without emitting, false otherwise",
		visual:      '',
		examples:    [
		{ title: "Basic Tapping for Side Effects", content: "import { of } from 'rxjs';\nimport { tap, map } from 'rxjs/operators';\n\nof(1, 2, 3, 4, 5).pipe(\n  tap(x => console.log('Before map:', x)),\n  map(x => x * 10),\n  tap(x => console.log('After map:', x))\n).subscribe(x => console.log('Final:', x));\n\n// Output:\n// Before map: 1\n// After map: 10\n// Final: 10\n// Before map: 2\n// After map: 20\n// Final: 20\n// ..." },
		{ title: "Advanced Tap with Observer", content: "import { of, throwError } from 'rxjs';\nimport { tap, catchError } from 'rxjs/operators';\n\nof(1, 2, 3).pipe(\n  tap({\n    next: value => console.log('Next:', value),\n    error: error => console.error('Error:', error),\n    complete: () => console.log('Complete!')\n  })\n).subscribe();\n\n// Output:\n// Next: 1\n// Next: 2\n// Next: 3\n// Complete!" }
		],
		seeAlso:     [],
		tags:        ["advanced","utilities"],
	}
]
